dist: bionic

language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake-data
      - cmake
      - libgmp-dev
      - libmpfr-dev
      - libicu-dev
      - gcc-9

script:
  - mkdir build && cd build
  - CC=gcc-9 CXX=g++-9 cmake .. -DCMAKE_BUILD_TYPE=Debug
  - cmake --build . -- -j4
