dist: bionic

language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake-data
      - cmake
      - libgmp-dev
      - libmpfr-dev
      - libflint-dev
      - libflint-arb-dev
      - libicu-dev
      - g++-9
      - libgccjit-9-dev

before_install:
  - eval "CC=gcc-9 && CXX=g++-9"

script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - cmake --build . -- -j4
